package helpers

var BaseStatsGenIII = map[string]map[string]int{
	"Bulbasaur": {
		HpString:             45,
		AttackString:         49,
		DefenseString:        49,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          45,
	},
	"Ivysaur": {
		HpString:             60,
		AttackString:         62,
		DefenseString:        63,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          60,
	},
	"Venusaur": {
		HpString:             80,
		AttackString:         82,
		DefenseString:        83,
		SpecialAttackString:  100,
		SpecialDefenseString: 100,
		SpeedString:          80,
	},
	"Charmander": {
		HpString:             39,
		AttackString:         52,
		DefenseString:        43,
		SpecialAttackString:  60,
		SpecialDefenseString: 50,
		SpeedString:          65,
	},
	"Charmeleon": {
		HpString:             58,
		AttackString:         64,
		DefenseString:        58,
		SpecialAttackString:  80,
		SpecialDefenseString: 65,
		SpeedString:          80,
	},
	"Charizard": {
		HpString:             78,
		AttackString:         84,
		DefenseString:        78,
		SpecialAttackString:  109,
		SpecialDefenseString: 85,
		SpeedString:          100,
	},
	"Squirtle": {
		HpString:             44,
		AttackString:         48,
		DefenseString:        65,
		SpecialAttackString:  50,
		SpecialDefenseString: 64,
		SpeedString:          43,
	},
	"Wartortle": {
		HpString:             59,
		AttackString:         63,
		DefenseString:        80,
		SpecialAttackString:  65,
		SpecialDefenseString: 80,
		SpeedString:          58,
	},
	"Blastoise": {
		HpString:             79,
		AttackString:         83,
		DefenseString:        100,
		SpecialAttackString:  85,
		SpecialDefenseString: 105,
		SpeedString:          78,
	},
	"Caterpie": {
		HpString:             45,
		AttackString:         30,
		DefenseString:        35,
		SpecialAttackString:  20,
		SpecialDefenseString: 20,
		SpeedString:          45,
	},
	"Metapod": {
		HpString:             50,
		AttackString:         20,
		DefenseString:        55,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          30,
	},
	"Butterfree": {
		HpString:             60,
		AttackString:         45,
		DefenseString:        50,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          70,
	},
	"Weedle": {
		HpString:             40,
		AttackString:         35,
		DefenseString:        30,
		SpecialAttackString:  20,
		SpecialDefenseString: 20,
		SpeedString:          50,
	},
	"Kakuna": {
		HpString:             45,
		AttackString:         25,
		DefenseString:        50,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          35,
	},
	"Beedrill": {
		HpString:             65,
		AttackString:         80,
		DefenseString:        40,
		SpecialAttackString:  45,
		SpecialDefenseString: 80,
		SpeedString:          75,
	},
	"Pidgey": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        40,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          56,
	},
	"Pidgeotto": {
		HpString:             63,
		AttackString:         60,
		DefenseString:        55,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          71,
	},
	"Pidgeot": {
		HpString:             83,
		AttackString:         80,
		DefenseString:        75,
		SpecialAttackString:  70,
		SpecialDefenseString: 70,
		SpeedString:          91,
	},
	"Rattata": {
		HpString:             30,
		AttackString:         56,
		DefenseString:        35,
		SpecialAttackString:  25,
		SpecialDefenseString: 35,
		SpeedString:          72,
	},
	"Raticate": {
		HpString:             55,
		AttackString:         81,
		DefenseString:        60,
		SpecialAttackString:  50,
		SpecialDefenseString: 70,
		SpeedString:          97,
	},
	"Spearow": {
		HpString:             40,
		AttackString:         60,
		DefenseString:        30,
		SpecialAttackString:  31,
		SpecialDefenseString: 31,
		SpeedString:          70,
	},
	"Fearow": {
		HpString:             65,
		AttackString:         90,
		DefenseString:        65,
		SpecialAttackString:  61,
		SpecialDefenseString: 61,
		SpeedString:          100,
	},
	"Ekans": {
		HpString:             35,
		AttackString:         60,
		DefenseString:        44,
		SpecialAttackString:  40,
		SpecialDefenseString: 54,
		SpeedString:          55,
	},
	"Arbok": {
		HpString:             60,
		AttackString:         85,
		DefenseString:        69,
		SpecialAttackString:  65,
		SpecialDefenseString: 79,
		SpeedString:          80,
	},
	"Pikachu": {
		HpString:             35,
		AttackString:         55,
		DefenseString:        30,
		SpecialAttackString:  50,
		SpecialDefenseString: 40,
		SpeedString:          90,
	},
	"Raichu": {
		HpString:             60,
		AttackString:         90,
		DefenseString:        55,
		SpecialAttackString:  90,
		SpecialDefenseString: 80,
		SpeedString:          100,
	},
	"Sandshrew": {
		HpString:             50,
		AttackString:         75,
		DefenseString:        85,
		SpecialAttackString:  20,
		SpecialDefenseString: 30,
		SpeedString:          40,
	},
	"Sandslash": {
		HpString:             75,
		AttackString:         100,
		DefenseString:        110,
		SpecialAttackString:  45,
		SpecialDefenseString: 55,
		SpeedString:          65,
	},
	"Nidoran-f": {
		HpString:             55,
		AttackString:         47,
		DefenseString:        52,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          41,
	},
	"Nidorina": {
		HpString:             70,
		AttackString:         62,
		DefenseString:        67,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          56,
	},
	"Nidoqueen": {
		HpString:             90,
		AttackString:         82,
		DefenseString:        87,
		SpecialAttackString:  75,
		SpecialDefenseString: 85,
		SpeedString:          76,
	},
	"Nidoran-m": {
		HpString:             46,
		AttackString:         57,
		DefenseString:        40,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          50,
	},
	"Nidorino": {
		HpString:             61,
		AttackString:         72,
		DefenseString:        57,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          65,
	},
	"Nidoking": {
		HpString:             81,
		AttackString:         92,
		DefenseString:        77,
		SpecialAttackString:  85,
		SpecialDefenseString: 75,
		SpeedString:          85,
	},
	"Clefairy": {
		HpString:             70,
		AttackString:         45,
		DefenseString:        48,
		SpecialAttackString:  60,
		SpecialDefenseString: 65,
		SpeedString:          35,
	},
	"Clefable": {
		HpString:             95,
		AttackString:         70,
		DefenseString:        73,
		SpecialAttackString:  85,
		SpecialDefenseString: 90,
		SpeedString:          60,
	},
	"Vulpix": {
		HpString:             38,
		AttackString:         41,
		DefenseString:        40,
		SpecialAttackString:  50,
		SpecialDefenseString: 65,
		SpeedString:          65,
	},
	"Ninetales": {
		HpString:             73,
		AttackString:         76,
		DefenseString:        75,
		SpecialAttackString:  81,
		SpecialDefenseString: 100,
		SpeedString:          100,
	},
	"Jigglypuff": {
		HpString:             115,
		AttackString:         45,
		DefenseString:        20,
		SpecialAttackString:  45,
		SpecialDefenseString: 25,
		SpeedString:          20,
	},
	"Wigglytuff": {
		HpString:             140,
		AttackString:         70,
		DefenseString:        45,
		SpecialAttackString:  75,
		SpecialDefenseString: 50,
		SpeedString:          45,
	},
	"Zubat": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        35,
		SpecialAttackString:  30,
		SpecialDefenseString: 40,
		SpeedString:          55,
	},
	"Golbat": {
		HpString:             75,
		AttackString:         80,
		DefenseString:        70,
		SpecialAttackString:  65,
		SpecialDefenseString: 75,
		SpeedString:          90,
	},
	"Oddish": {
		HpString:             45,
		AttackString:         50,
		DefenseString:        55,
		SpecialAttackString:  75,
		SpecialDefenseString: 65,
		SpeedString:          30,
	},
	"Gloom": {
		HpString:             60,
		AttackString:         65,
		DefenseString:        70,
		SpecialAttackString:  85,
		SpecialDefenseString: 75,
		SpeedString:          40,
	},
	"Vileplume": {
		HpString:             75,
		AttackString:         80,
		DefenseString:        85,
		SpecialAttackString:  100,
		SpecialDefenseString: 90,
		SpeedString:          50,
	},
	"Paras": {
		HpString:             35,
		AttackString:         70,
		DefenseString:        55,
		SpecialAttackString:  45,
		SpecialDefenseString: 55,
		SpeedString:          25,
	},
	"Parasect": {
		HpString:             60,
		AttackString:         95,
		DefenseString:        80,
		SpecialAttackString:  60,
		SpecialDefenseString: 80,
		SpeedString:          30,
	},
	"Venonat": {
		HpString:             60,
		AttackString:         55,
		DefenseString:        50,
		SpecialAttackString:  40,
		SpecialDefenseString: 55,
		SpeedString:          45,
	},
	"Venomoth": {
		HpString:             70,
		AttackString:         65,
		DefenseString:        60,
		SpecialAttackString:  90,
		SpecialDefenseString: 75,
		SpeedString:          90,
	},
	"Diglett": {
		HpString:             10,
		AttackString:         55,
		DefenseString:        25,
		SpecialAttackString:  35,
		SpecialDefenseString: 45,
		SpeedString:          95,
	},
	"Dugtrio": {
		HpString:             35,
		AttackString:         80,
		DefenseString:        50,
		SpecialAttackString:  50,
		SpecialDefenseString: 70,
		SpeedString:          120,
	},
	"Meowth": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        35,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          90,
	},
	"Persian": {
		HpString:             65,
		AttackString:         70,
		DefenseString:        60,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          115,
	},
	"Psyduck": {
		HpString:             50,
		AttackString:         52,
		DefenseString:        48,
		SpecialAttackString:  65,
		SpecialDefenseString: 50,
		SpeedString:          55,
	},
	"Golduck": {
		HpString:             80,
		AttackString:         82,
		DefenseString:        78,
		SpecialAttackString:  95,
		SpecialDefenseString: 80,
		SpeedString:          85,
	},
	"Mankey": {
		HpString:             40,
		AttackString:         80,
		DefenseString:        35,
		SpecialAttackString:  35,
		SpecialDefenseString: 45,
		SpeedString:          70,
	},
	"Primeape": {
		HpString:             65,
		AttackString:         105,
		DefenseString:        60,
		SpecialAttackString:  60,
		SpecialDefenseString: 70,
		SpeedString:          95,
	},
	"Growlithe": {
		HpString:             55,
		AttackString:         70,
		DefenseString:        45,
		SpecialAttackString:  70,
		SpecialDefenseString: 50,
		SpeedString:          60,
	},
	"Arcanine": {
		HpString:             90,
		AttackString:         110,
		DefenseString:        80,
		SpecialAttackString:  100,
		SpecialDefenseString: 80,
		SpeedString:          95,
	},
	"Poliwag": {
		HpString:             40,
		AttackString:         50,
		DefenseString:        40,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          90,
	},
	"Poliwhirl": {
		HpString:             65,
		AttackString:         65,
		DefenseString:        65,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          90,
	},
	"Poliwrath": {
		HpString:             90,
		AttackString:         85,
		DefenseString:        95,
		SpecialAttackString:  70,
		SpecialDefenseString: 90,
		SpeedString:          70,
	},
	"Abra": {
		HpString:             25,
		AttackString:         20,
		DefenseString:        15,
		SpecialAttackString:  105,
		SpecialDefenseString: 55,
		SpeedString:          90,
	},
	"Kadabra": {
		HpString:             40,
		AttackString:         35,
		DefenseString:        30,
		SpecialAttackString:  120,
		SpecialDefenseString: 70,
		SpeedString:          105,
	},
	"Alakazam": {
		HpString:             55,
		AttackString:         50,
		DefenseString:        45,
		SpecialAttackString:  135,
		SpecialDefenseString: 85,
		SpeedString:          120,
	},
	"Machop": {
		HpString:             70,
		AttackString:         80,
		DefenseString:        50,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          35,
	},
	"Machoke": {
		HpString:             80,
		AttackString:         100,
		DefenseString:        70,
		SpecialAttackString:  50,
		SpecialDefenseString: 60,
		SpeedString:          45,
	},
	"Machamp": {
		HpString:             90,
		AttackString:         130,
		DefenseString:        80,
		SpecialAttackString:  65,
		SpecialDefenseString: 85,
		SpeedString:          55,
	},
	"Bellsprout": {
		HpString:             50,
		AttackString:         75,
		DefenseString:        35,
		SpecialAttackString:  70,
		SpecialDefenseString: 30,
		SpeedString:          40,
	},
	"Weepinbell": {
		HpString:             65,
		AttackString:         90,
		DefenseString:        50,
		SpecialAttackString:  85,
		SpecialDefenseString: 45,
		SpeedString:          55,
	},
	"Victreebel": {
		HpString:             80,
		AttackString:         105,
		DefenseString:        65,
		SpecialAttackString:  100,
		SpecialDefenseString: 60,
		SpeedString:          70,
	},
	"Tentacool": {
		HpString:             40,
		AttackString:         40,
		DefenseString:        35,
		SpecialAttackString:  50,
		SpecialDefenseString: 100,
		SpeedString:          70,
	},
	"Tentacruel": {
		HpString:             80,
		AttackString:         70,
		DefenseString:        65,
		SpecialAttackString:  80,
		SpecialDefenseString: 120,
		SpeedString:          100,
	},
	"Geodude": {
		HpString:             40,
		AttackString:         80,
		DefenseString:        100,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          20,
	},
	"Graveler": {
		HpString:             55,
		AttackString:         95,
		DefenseString:        115,
		SpecialAttackString:  45,
		SpecialDefenseString: 45,
		SpeedString:          35,
	},
	"Golem": {
		HpString:             80,
		AttackString:         110,
		DefenseString:        130,
		SpecialAttackString:  55,
		SpecialDefenseString: 65,
		SpeedString:          45,
	},
	"Ponyta": {
		HpString:             50,
		AttackString:         85,
		DefenseString:        55,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          90,
	},
	"Rapidash": {
		HpString:             65,
		AttackString:         100,
		DefenseString:        70,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          105,
	},
	"Slowpoke": {
		HpString:             90,
		AttackString:         65,
		DefenseString:        65,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          15,
	},
	"Slowbro": {
		HpString:             95,
		AttackString:         75,
		DefenseString:        110,
		SpecialAttackString:  100,
		SpecialDefenseString: 80,
		SpeedString:          30,
	},
	"Magnemite": {
		HpString:             25,
		AttackString:         35,
		DefenseString:        70,
		SpecialAttackString:  95,
		SpecialDefenseString: 55,
		SpeedString:          45,
	},
	"Magneton": {
		HpString:             50,
		AttackString:         60,
		DefenseString:        95,
		SpecialAttackString:  120,
		SpecialDefenseString: 70,
		SpeedString:          70,
	},
	"Farfetchd": {
		HpString:             52,
		AttackString:         65,
		DefenseString:        55,
		SpecialAttackString:  58,
		SpecialDefenseString: 62,
		SpeedString:          60,
	},
	"Doduo": {
		HpString:             35,
		AttackString:         85,
		DefenseString:        45,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          75,
	},
	"Dodrio": {
		HpString:             60,
		AttackString:         110,
		DefenseString:        70,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          100,
	},
	"Seel": {
		HpString:             65,
		AttackString:         45,
		DefenseString:        55,
		SpecialAttackString:  45,
		SpecialDefenseString: 70,
		SpeedString:          45,
	},
	"Dewgong": {
		HpString:             90,
		AttackString:         70,
		DefenseString:        80,
		SpecialAttackString:  70,
		SpecialDefenseString: 95,
		SpeedString:          70,
	},
	"Grimer": {
		HpString:             80,
		AttackString:         80,
		DefenseString:        50,
		SpecialAttackString:  40,
		SpecialDefenseString: 50,
		SpeedString:          25,
	},
	"Muk": {
		HpString:             105,
		AttackString:         105,
		DefenseString:        75,
		SpecialAttackString:  65,
		SpecialDefenseString: 100,
		SpeedString:          50,
	},
	"Shellder": {
		HpString:             30,
		AttackString:         65,
		DefenseString:        100,
		SpecialAttackString:  45,
		SpecialDefenseString: 25,
		SpeedString:          40,
	},
	"Cloyster": {
		HpString:             50,
		AttackString:         95,
		DefenseString:        180,
		SpecialAttackString:  85,
		SpecialDefenseString: 45,
		SpeedString:          70,
	},
	"Gastly": {
		HpString:             30,
		AttackString:         35,
		DefenseString:        30,
		SpecialAttackString:  100,
		SpecialDefenseString: 35,
		SpeedString:          80,
	},
	"Haunter": {
		HpString:             45,
		AttackString:         50,
		DefenseString:        45,
		SpecialAttackString:  115,
		SpecialDefenseString: 55,
		SpeedString:          95,
	},
	"Gengar": {
		HpString:             60,
		AttackString:         65,
		DefenseString:        60,
		SpecialAttackString:  130,
		SpecialDefenseString: 75,
		SpeedString:          110,
	},
	"Onix": {
		HpString:             35,
		AttackString:         45,
		DefenseString:        160,
		SpecialAttackString:  30,
		SpecialDefenseString: 45,
		SpeedString:          70,
	},
	"Drowzee": {
		HpString:             60,
		AttackString:         48,
		DefenseString:        45,
		SpecialAttackString:  43,
		SpecialDefenseString: 90,
		SpeedString:          42,
	},
	"Hypno": {
		HpString:             85,
		AttackString:         73,
		DefenseString:        70,
		SpecialAttackString:  73,
		SpecialDefenseString: 115,
		SpeedString:          67,
	},
	"Krabby": {
		HpString:             30,
		AttackString:         105,
		DefenseString:        90,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          50,
	},
	"Kingler": {
		HpString:             55,
		AttackString:         130,
		DefenseString:        115,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          75,
	},
	"Voltorb": {
		HpString:             40,
		AttackString:         30,
		DefenseString:        50,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          100,
	},
	"Electrode": {
		HpString:             60,
		AttackString:         50,
		DefenseString:        70,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          140,
	},
	"Exeggcute": {
		HpString:             60,
		AttackString:         40,
		DefenseString:        80,
		SpecialAttackString:  60,
		SpecialDefenseString: 45,
		SpeedString:          40,
	},
	"Exeggutor": {
		HpString:             95,
		AttackString:         95,
		DefenseString:        85,
		SpecialAttackString:  125,
		SpecialDefenseString: 65,
		SpeedString:          55,
	},
	"Cubone": {
		HpString:             50,
		AttackString:         50,
		DefenseString:        95,
		SpecialAttackString:  40,
		SpecialDefenseString: 50,
		SpeedString:          35,
	},
	"Marowak": {
		HpString:             60,
		AttackString:         80,
		DefenseString:        110,
		SpecialAttackString:  50,
		SpecialDefenseString: 80,
		SpeedString:          45,
	},
	"Hitmonlee": {
		HpString:             50,
		AttackString:         120,
		DefenseString:        53,
		SpecialAttackString:  35,
		SpecialDefenseString: 110,
		SpeedString:          87,
	},
	"Hitmonchan": {
		HpString:             50,
		AttackString:         105,
		DefenseString:        79,
		SpecialAttackString:  35,
		SpecialDefenseString: 110,
		SpeedString:          76,
	},
	"Lickitung": {
		HpString:             90,
		AttackString:         55,
		DefenseString:        75,
		SpecialAttackString:  60,
		SpecialDefenseString: 75,
		SpeedString:          30,
	},
	"Koffing": {
		HpString:             40,
		AttackString:         65,
		DefenseString:        95,
		SpecialAttackString:  60,
		SpecialDefenseString: 45,
		SpeedString:          35,
	},
	"Weezing": {
		HpString:             65,
		AttackString:         90,
		DefenseString:        120,
		SpecialAttackString:  85,
		SpecialDefenseString: 70,
		SpeedString:          60,
	},
	"Rhyhorn": {
		HpString:             80,
		AttackString:         85,
		DefenseString:        95,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          25,
	},
	"Rhydon": {
		HpString:             105,
		AttackString:         130,
		DefenseString:        120,
		SpecialAttackString:  45,
		SpecialDefenseString: 45,
		SpeedString:          40,
	},
	"Chansey": {
		HpString:             250,
		AttackString:         5,
		DefenseString:        5,
		SpecialAttackString:  35,
		SpecialDefenseString: 105,
		SpeedString:          50,
	},
	"Tangela": {
		HpString:             65,
		AttackString:         55,
		DefenseString:        115,
		SpecialAttackString:  100,
		SpecialDefenseString: 40,
		SpeedString:          60,
	},
	"Kangaskhan": {
		HpString:             105,
		AttackString:         95,
		DefenseString:        80,
		SpecialAttackString:  40,
		SpecialDefenseString: 80,
		SpeedString:          90,
	},
	"Horsea": {
		HpString:             30,
		AttackString:         40,
		DefenseString:        70,
		SpecialAttackString:  70,
		SpecialDefenseString: 25,
		SpeedString:          60,
	},
	"Seadra": {
		HpString:             55,
		AttackString:         65,
		DefenseString:        95,
		SpecialAttackString:  95,
		SpecialDefenseString: 45,
		SpeedString:          85,
	},
	"Goldeen": {
		HpString:             45,
		AttackString:         67,
		DefenseString:        60,
		SpecialAttackString:  35,
		SpecialDefenseString: 50,
		SpeedString:          63,
	},
	"Seaking": {
		HpString:             80,
		AttackString:         92,
		DefenseString:        65,
		SpecialAttackString:  65,
		SpecialDefenseString: 80,
		SpeedString:          68,
	},
	"Staryu": {
		HpString:             30,
		AttackString:         45,
		DefenseString:        55,
		SpecialAttackString:  70,
		SpecialDefenseString: 55,
		SpeedString:          85,
	},
	"Starmie": {
		HpString:             60,
		AttackString:         75,
		DefenseString:        85,
		SpecialAttackString:  100,
		SpecialDefenseString: 85,
		SpeedString:          115,
	},
	"Mr-mime": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        65,
		SpecialAttackString:  100,
		SpecialDefenseString: 120,
		SpeedString:          90,
	},
	"Scyther": {
		HpString:             70,
		AttackString:         110,
		DefenseString:        80,
		SpecialAttackString:  55,
		SpecialDefenseString: 80,
		SpeedString:          105,
	},
	"Jynx": {
		HpString:             65,
		AttackString:         50,
		DefenseString:        35,
		SpecialAttackString:  115,
		SpecialDefenseString: 95,
		SpeedString:          95,
	},
	"Electabuzz": {
		HpString:             65,
		AttackString:         83,
		DefenseString:        57,
		SpecialAttackString:  95,
		SpecialDefenseString: 85,
		SpeedString:          105,
	},
	"Magmar": {
		HpString:             65,
		AttackString:         95,
		DefenseString:        57,
		SpecialAttackString:  100,
		SpecialDefenseString: 85,
		SpeedString:          93,
	},
	"Pinsir": {
		HpString:             65,
		AttackString:         125,
		DefenseString:        100,
		SpecialAttackString:  55,
		SpecialDefenseString: 70,
		SpeedString:          85,
	},
	"Tauros": {
		HpString:             75,
		AttackString:         100,
		DefenseString:        95,
		SpecialAttackString:  40,
		SpecialDefenseString: 70,
		SpeedString:          110,
	},
	"Magikarp": {
		HpString:             20,
		AttackString:         10,
		DefenseString:        55,
		SpecialAttackString:  15,
		SpecialDefenseString: 20,
		SpeedString:          80,
	},
	"Gyarados": {
		HpString:             95,
		AttackString:         125,
		DefenseString:        79,
		SpecialAttackString:  60,
		SpecialDefenseString: 100,
		SpeedString:          81,
	},
	"Lapras": {
		HpString:             130,
		AttackString:         85,
		DefenseString:        80,
		SpecialAttackString:  85,
		SpecialDefenseString: 95,
		SpeedString:          60,
	},
	"Ditto": {
		HpString:             48,
		AttackString:         48,
		DefenseString:        48,
		SpecialAttackString:  48,
		SpecialDefenseString: 48,
		SpeedString:          48,
	},
	"Eevee": {
		HpString:             55,
		AttackString:         55,
		DefenseString:        50,
		SpecialAttackString:  45,
		SpecialDefenseString: 65,
		SpeedString:          55,
	},
	"Vaporeon": {
		HpString:             130,
		AttackString:         65,
		DefenseString:        60,
		SpecialAttackString:  110,
		SpecialDefenseString: 95,
		SpeedString:          65,
	},
	"Jolteon": {
		HpString:             65,
		AttackString:         65,
		DefenseString:        60,
		SpecialAttackString:  110,
		SpecialDefenseString: 95,
		SpeedString:          130,
	},
	"Flareon": {
		HpString:             65,
		AttackString:         130,
		DefenseString:        60,
		SpecialAttackString:  95,
		SpecialDefenseString: 110,
		SpeedString:          65,
	},
	"Porygon": {
		HpString:             65,
		AttackString:         60,
		DefenseString:        70,
		SpecialAttackString:  85,
		SpecialDefenseString: 75,
		SpeedString:          40,
	},
	"Omanyte": {
		HpString:             35,
		AttackString:         40,
		DefenseString:        100,
		SpecialAttackString:  90,
		SpecialDefenseString: 55,
		SpeedString:          35,
	},
	"Omastar": {
		HpString:             70,
		AttackString:         60,
		DefenseString:        125,
		SpecialAttackString:  115,
		SpecialDefenseString: 70,
		SpeedString:          55,
	},
	"Kabuto": {
		HpString:             30,
		AttackString:         80,
		DefenseString:        90,
		SpecialAttackString:  55,
		SpecialDefenseString: 45,
		SpeedString:          55,
	},
	"Kabutops": {
		HpString:             60,
		AttackString:         115,
		DefenseString:        105,
		SpecialAttackString:  65,
		SpecialDefenseString: 70,
		SpeedString:          80,
	},
	"Aerodactyl": {
		HpString:             80,
		AttackString:         105,
		DefenseString:        65,
		SpecialAttackString:  60,
		SpecialDefenseString: 75,
		SpeedString:          130,
	},
	"Snorlax": {
		HpString:             160,
		AttackString:         110,
		DefenseString:        65,
		SpecialAttackString:  65,
		SpecialDefenseString: 110,
		SpeedString:          30,
	},
	"Articuno": {
		HpString:             90,
		AttackString:         85,
		DefenseString:        100,
		SpecialAttackString:  95,
		SpecialDefenseString: 125,
		SpeedString:          85,
	},
	"Zapdos": {
		HpString:             90,
		AttackString:         90,
		DefenseString:        85,
		SpecialAttackString:  125,
		SpecialDefenseString: 90,
		SpeedString:          100,
	},
	"Moltres": {
		HpString:             90,
		AttackString:         100,
		DefenseString:        90,
		SpecialAttackString:  125,
		SpecialDefenseString: 85,
		SpeedString:          90,
	},
	"Dratini": {
		HpString:             41,
		AttackString:         64,
		DefenseString:        45,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          50,
	},
	"Dragonair": {
		HpString:             61,
		AttackString:         84,
		DefenseString:        65,
		SpecialAttackString:  70,
		SpecialDefenseString: 70,
		SpeedString:          70,
	},
	"Dragonite": {
		HpString:             91,
		AttackString:         134,
		DefenseString:        95,
		SpecialAttackString:  100,
		SpecialDefenseString: 100,
		SpeedString:          80,
	},
	"Mewtwo": {
		HpString:             106,
		AttackString:         110,
		DefenseString:        90,
		SpecialAttackString:  154,
		SpecialDefenseString: 90,
		SpeedString:          130,
	},
	"Mew": {
		HpString:             100,
		AttackString:         100,
		DefenseString:        100,
		SpecialAttackString:  100,
		SpecialDefenseString: 100,
		SpeedString:          100,
	},
	"Chikorita": {
		HpString:             45,
		AttackString:         49,
		DefenseString:        65,
		SpecialAttackString:  49,
		SpecialDefenseString: 65,
		SpeedString:          45,
	},
	"Bayleef": {
		HpString:             60,
		AttackString:         62,
		DefenseString:        80,
		SpecialAttackString:  63,
		SpecialDefenseString: 80,
		SpeedString:          60,
	},
	"Meganium": {
		HpString:             80,
		AttackString:         82,
		DefenseString:        100,
		SpecialAttackString:  83,
		SpecialDefenseString: 100,
		SpeedString:          80,
	},
	"Cyndaquil": {
		HpString:             39,
		AttackString:         52,
		DefenseString:        43,
		SpecialAttackString:  60,
		SpecialDefenseString: 50,
		SpeedString:          65,
	},
	"Quilava": {
		HpString:             58,
		AttackString:         64,
		DefenseString:        58,
		SpecialAttackString:  80,
		SpecialDefenseString: 65,
		SpeedString:          80,
	},
	"Typhlosion": {
		HpString:             78,
		AttackString:         84,
		DefenseString:        78,
		SpecialAttackString:  109,
		SpecialDefenseString: 85,
		SpeedString:          100,
	},
	"Totodile": {
		HpString:             50,
		AttackString:         65,
		DefenseString:        64,
		SpecialAttackString:  44,
		SpecialDefenseString: 48,
		SpeedString:          43,
	},
	"Croconaw": {
		HpString:             65,
		AttackString:         80,
		DefenseString:        80,
		SpecialAttackString:  59,
		SpecialDefenseString: 63,
		SpeedString:          58,
	},
	"Feraligatr": {
		HpString:             85,
		AttackString:         105,
		DefenseString:        100,
		SpecialAttackString:  79,
		SpecialDefenseString: 83,
		SpeedString:          78,
	},
	"Sentret": {
		HpString:             35,
		AttackString:         46,
		DefenseString:        34,
		SpecialAttackString:  35,
		SpecialDefenseString: 45,
		SpeedString:          20,
	},
	"Furret": {
		HpString:             85,
		AttackString:         76,
		DefenseString:        64,
		SpecialAttackString:  45,
		SpecialDefenseString: 55,
		SpeedString:          90,
	},
	"Hoothoot": {
		HpString:             60,
		AttackString:         30,
		DefenseString:        30,
		SpecialAttackString:  36,
		SpecialDefenseString: 56,
		SpeedString:          50,
	},
	"Noctowl": {
		HpString:             100,
		AttackString:         50,
		DefenseString:        50,
		SpecialAttackString:  76,
		SpecialDefenseString: 96,
		SpeedString:          70,
	},
	"Ledyba": {
		HpString:             40,
		AttackString:         20,
		DefenseString:        30,
		SpecialAttackString:  40,
		SpecialDefenseString: 80,
		SpeedString:          55,
	},
	"Ledian": {
		HpString:             55,
		AttackString:         35,
		DefenseString:        50,
		SpecialAttackString:  55,
		SpecialDefenseString: 110,
		SpeedString:          85,
	},
	"Spinarak": {
		HpString:             40,
		AttackString:         60,
		DefenseString:        40,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          30,
	},
	"Ariados": {
		HpString:             70,
		AttackString:         90,
		DefenseString:        70,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          40,
	},
	"Crobat": {
		HpString:             85,
		AttackString:         90,
		DefenseString:        80,
		SpecialAttackString:  70,
		SpecialDefenseString: 80,
		SpeedString:          130,
	},
	"Chinchou": {
		HpString:             75,
		AttackString:         38,
		DefenseString:        38,
		SpecialAttackString:  56,
		SpecialDefenseString: 56,
		SpeedString:          67,
	},
	"Lanturn": {
		HpString:             125,
		AttackString:         58,
		DefenseString:        58,
		SpecialAttackString:  76,
		SpecialDefenseString: 76,
		SpeedString:          67,
	},
	"Pichu": {
		HpString:             20,
		AttackString:         40,
		DefenseString:        15,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          60,
	},
	"Cleffa": {
		HpString:             50,
		AttackString:         25,
		DefenseString:        28,
		SpecialAttackString:  45,
		SpecialDefenseString: 55,
		SpeedString:          15,
	},
	"Igglybuff": {
		HpString:             90,
		AttackString:         30,
		DefenseString:        15,
		SpecialAttackString:  40,
		SpecialDefenseString: 20,
		SpeedString:          15,
	},
	"Togepi": {
		HpString:             35,
		AttackString:         20,
		DefenseString:        65,
		SpecialAttackString:  40,
		SpecialDefenseString: 65,
		SpeedString:          20,
	},
	"Togetic": {
		HpString:             55,
		AttackString:         40,
		DefenseString:        85,
		SpecialAttackString:  80,
		SpecialDefenseString: 105,
		SpeedString:          40,
	},
	"Natu": {
		HpString:             40,
		AttackString:         50,
		DefenseString:        45,
		SpecialAttackString:  70,
		SpecialDefenseString: 45,
		SpeedString:          70,
	},
	"Xatu": {
		HpString:             65,
		AttackString:         75,
		DefenseString:        70,
		SpecialAttackString:  95,
		SpecialDefenseString: 70,
		SpeedString:          95,
	},
	"Mareep": {
		HpString:             55,
		AttackString:         40,
		DefenseString:        40,
		SpecialAttackString:  65,
		SpecialDefenseString: 45,
		SpeedString:          35,
	},
	"Flaaffy": {
		HpString:             70,
		AttackString:         55,
		DefenseString:        55,
		SpecialAttackString:  80,
		SpecialDefenseString: 60,
		SpeedString:          45,
	},
	"Ampharos": {
		HpString:             90,
		AttackString:         75,
		DefenseString:        75,
		SpecialAttackString:  115,
		SpecialDefenseString: 90,
		SpeedString:          55,
	},
	"Bellossom": {
		HpString:             75,
		AttackString:         80,
		DefenseString:        85,
		SpecialAttackString:  90,
		SpecialDefenseString: 100,
		SpeedString:          50,
	},
	"Marill": {
		HpString:             70,
		AttackString:         20,
		DefenseString:        50,
		SpecialAttackString:  20,
		SpecialDefenseString: 50,
		SpeedString:          40,
	},
	"Azumarill": {
		HpString:             100,
		AttackString:         50,
		DefenseString:        80,
		SpecialAttackString:  50,
		SpecialDefenseString: 80,
		SpeedString:          50,
	},
	"Sudowoodo": {
		HpString:             70,
		AttackString:         100,
		DefenseString:        115,
		SpecialAttackString:  30,
		SpecialDefenseString: 65,
		SpeedString:          30,
	},
	"Politoed": {
		HpString:             90,
		AttackString:         75,
		DefenseString:        75,
		SpecialAttackString:  90,
		SpecialDefenseString: 100,
		SpeedString:          70,
	},
	"Hoppip": {
		HpString:             35,
		AttackString:         35,
		DefenseString:        40,
		SpecialAttackString:  35,
		SpecialDefenseString: 55,
		SpeedString:          50,
	},
	"Skiploom": {
		HpString:             55,
		AttackString:         45,
		DefenseString:        50,
		SpecialAttackString:  45,
		SpecialDefenseString: 65,
		SpeedString:          80,
	},
	"Jumpluff": {
		HpString:             75,
		AttackString:         55,
		DefenseString:        70,
		SpecialAttackString:  55,
		SpecialDefenseString: 85,
		SpeedString:          110,
	},
	"Aipom": {
		HpString:             55,
		AttackString:         70,
		DefenseString:        55,
		SpecialAttackString:  40,
		SpecialDefenseString: 55,
		SpeedString:          85,
	},
	"Sunkern": {
		HpString:             30,
		AttackString:         30,
		DefenseString:        30,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          30,
	},
	"Sunflora": {
		HpString:             75,
		AttackString:         75,
		DefenseString:        55,
		SpecialAttackString:  105,
		SpecialDefenseString: 85,
		SpeedString:          30,
	},
	"Yanma": {
		HpString:             65,
		AttackString:         65,
		DefenseString:        45,
		SpecialAttackString:  75,
		SpecialDefenseString: 45,
		SpeedString:          95,
	},
	"Wooper": {
		HpString:             55,
		AttackString:         45,
		DefenseString:        45,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          15,
	},
	"Quagsire": {
		HpString:             95,
		AttackString:         85,
		DefenseString:        85,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          35,
	},
	"Espeon": {
		HpString:             65,
		AttackString:         65,
		DefenseString:        60,
		SpecialAttackString:  130,
		SpecialDefenseString: 95,
		SpeedString:          110,
	},
	"Umbreon": {
		HpString:             95,
		AttackString:         65,
		DefenseString:        110,
		SpecialAttackString:  60,
		SpecialDefenseString: 130,
		SpeedString:          65,
	},
	"Murkrow": {
		HpString:             60,
		AttackString:         85,
		DefenseString:        42,
		SpecialAttackString:  85,
		SpecialDefenseString: 42,
		SpeedString:          91,
	},
	"Slowking": {
		HpString:             95,
		AttackString:         75,
		DefenseString:        80,
		SpecialAttackString:  100,
		SpecialDefenseString: 110,
		SpeedString:          30,
	},
	"Misdreavus": {
		HpString:             60,
		AttackString:         60,
		DefenseString:        60,
		SpecialAttackString:  85,
		SpecialDefenseString: 85,
		SpeedString:          85,
	},
	"Unown": {
		HpString:             48,
		AttackString:         72,
		DefenseString:        48,
		SpecialAttackString:  72,
		SpecialDefenseString: 48,
		SpeedString:          48,
	},
	"Wobbuffet": {
		HpString:             190,
		AttackString:         33,
		DefenseString:        58,
		SpecialAttackString:  33,
		SpecialDefenseString: 58,
		SpeedString:          33,
	},
	"Girafarig": {
		HpString:             70,
		AttackString:         80,
		DefenseString:        65,
		SpecialAttackString:  90,
		SpecialDefenseString: 65,
		SpeedString:          85,
	},
	"Pineco": {
		HpString:             50,
		AttackString:         65,
		DefenseString:        90,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          15,
	},
	"Forretress": {
		HpString:             75,
		AttackString:         90,
		DefenseString:        140,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          40,
	},
	"Dunsparce": {
		HpString:             100,
		AttackString:         70,
		DefenseString:        70,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          45,
	},
	"Gligar": {
		HpString:             65,
		AttackString:         75,
		DefenseString:        105,
		SpecialAttackString:  35,
		SpecialDefenseString: 65,
		SpeedString:          85,
	},
	"Steelix": {
		HpString:             75,
		AttackString:         85,
		DefenseString:        200,
		SpecialAttackString:  55,
		SpecialDefenseString: 65,
		SpeedString:          30,
	},
	"Snubbull": {
		HpString:             60,
		AttackString:         80,
		DefenseString:        50,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          30,
	},
	"Granbull": {
		HpString:             90,
		AttackString:         120,
		DefenseString:        75,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          45,
	},
	"Qwilfish": {
		HpString:             65,
		AttackString:         95,
		DefenseString:        75,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          85,
	},
	"Scizor": {
		HpString:             70,
		AttackString:         130,
		DefenseString:        100,
		SpecialAttackString:  55,
		SpecialDefenseString: 80,
		SpeedString:          65,
	},
	"Shuckle": {
		HpString:             20,
		AttackString:         10,
		DefenseString:        230,
		SpecialAttackString:  10,
		SpecialDefenseString: 230,
		SpeedString:          5,
	},
	"Heracross": {
		HpString:             80,
		AttackString:         125,
		DefenseString:        75,
		SpecialAttackString:  40,
		SpecialDefenseString: 95,
		SpeedString:          85,
	},
	"Sneasel": {
		HpString:             55,
		AttackString:         95,
		DefenseString:        55,
		SpecialAttackString:  35,
		SpecialDefenseString: 75,
		SpeedString:          115,
	},
	"Teddiursa": {
		HpString:             60,
		AttackString:         80,
		DefenseString:        50,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          40,
	},
	"Ursaring": {
		HpString:             90,
		AttackString:         130,
		DefenseString:        75,
		SpecialAttackString:  75,
		SpecialDefenseString: 75,
		SpeedString:          55,
	},
	"Slugma": {
		HpString:             40,
		AttackString:         40,
		DefenseString:        40,
		SpecialAttackString:  70,
		SpecialDefenseString: 40,
		SpeedString:          20,
	},
	"Magcargo": {
		HpString:             50,
		AttackString:         50,
		DefenseString:        120,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          30,
	},
	"Swinub": {
		HpString:             50,
		AttackString:         50,
		DefenseString:        40,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          50,
	},
	"Piloswine": {
		HpString:             100,
		AttackString:         100,
		DefenseString:        80,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          50,
	},
	"Corsola": {
		HpString:             55,
		AttackString:         55,
		DefenseString:        85,
		SpecialAttackString:  65,
		SpecialDefenseString: 85,
		SpeedString:          35,
	},
	"Remoraid": {
		HpString:             35,
		AttackString:         65,
		DefenseString:        35,
		SpecialAttackString:  65,
		SpecialDefenseString: 35,
		SpeedString:          65,
	},
	"Octillery": {
		HpString:             75,
		AttackString:         105,
		DefenseString:        75,
		SpecialAttackString:  105,
		SpecialDefenseString: 75,
		SpeedString:          45,
	},
	"Delibird": {
		HpString:             45,
		AttackString:         55,
		DefenseString:        45,
		SpecialAttackString:  65,
		SpecialDefenseString: 45,
		SpeedString:          75,
	},
	"Mantine": {
		HpString:             65,
		AttackString:         40,
		DefenseString:        70,
		SpecialAttackString:  80,
		SpecialDefenseString: 140,
		SpeedString:          70,
	},
	"Skarmory": {
		HpString:             65,
		AttackString:         80,
		DefenseString:        140,
		SpecialAttackString:  40,
		SpecialDefenseString: 70,
		SpeedString:          70,
	},
	"Houndour": {
		HpString:             45,
		AttackString:         60,
		DefenseString:        30,
		SpecialAttackString:  80,
		SpecialDefenseString: 50,
		SpeedString:          65,
	},
	"Houndoom": {
		HpString:             75,
		AttackString:         90,
		DefenseString:        50,
		SpecialAttackString:  110,
		SpecialDefenseString: 80,
		SpeedString:          95,
	},
	"Kingdra": {
		HpString:             75,
		AttackString:         95,
		DefenseString:        95,
		SpecialAttackString:  95,
		SpecialDefenseString: 95,
		SpeedString:          85,
	},
	"Phanpy": {
		HpString:             90,
		AttackString:         60,
		DefenseString:        60,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          40,
	},
	"Donphan": {
		HpString:             90,
		AttackString:         120,
		DefenseString:        120,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          50,
	},
	"Porygon2": {
		HpString:             85,
		AttackString:         80,
		DefenseString:        90,
		SpecialAttackString:  105,
		SpecialDefenseString: 95,
		SpeedString:          60,
	},
	"Stantler": {
		HpString:             73,
		AttackString:         95,
		DefenseString:        62,
		SpecialAttackString:  85,
		SpecialDefenseString: 65,
		SpeedString:          85,
	},
	"Smeargle": {
		HpString:             55,
		AttackString:         20,
		DefenseString:        35,
		SpecialAttackString:  20,
		SpecialDefenseString: 45,
		SpeedString:          75,
	},
	"Tyrogue": {
		HpString:             35,
		AttackString:         35,
		DefenseString:        35,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          35,
	},
	"Hitmontop": {
		HpString:             50,
		AttackString:         95,
		DefenseString:        95,
		SpecialAttackString:  35,
		SpecialDefenseString: 110,
		SpeedString:          70,
	},
	"Smoochum": {
		HpString:             45,
		AttackString:         30,
		DefenseString:        15,
		SpecialAttackString:  85,
		SpecialDefenseString: 65,
		SpeedString:          65,
	},
	"Elekid": {
		HpString:             45,
		AttackString:         63,
		DefenseString:        37,
		SpecialAttackString:  65,
		SpecialDefenseString: 55,
		SpeedString:          95,
	},
	"Magby": {
		HpString:             45,
		AttackString:         75,
		DefenseString:        37,
		SpecialAttackString:  70,
		SpecialDefenseString: 55,
		SpeedString:          83,
	},
	"Miltank": {
		HpString:             95,
		AttackString:         80,
		DefenseString:        105,
		SpecialAttackString:  40,
		SpecialDefenseString: 70,
		SpeedString:          100,
	},
	"Blissey": {
		HpString:             255,
		AttackString:         10,
		DefenseString:        10,
		SpecialAttackString:  75,
		SpecialDefenseString: 135,
		SpeedString:          55,
	},
	"Raikou": {
		HpString:             90,
		AttackString:         85,
		DefenseString:        75,
		SpecialAttackString:  115,
		SpecialDefenseString: 100,
		SpeedString:          115,
	},
	"Entei": {
		HpString:             115,
		AttackString:         115,
		DefenseString:        85,
		SpecialAttackString:  90,
		SpecialDefenseString: 75,
		SpeedString:          100,
	},
	"Suicune": {
		HpString:             100,
		AttackString:         75,
		DefenseString:        115,
		SpecialAttackString:  90,
		SpecialDefenseString: 115,
		SpeedString:          85,
	},
	"Larvitar": {
		HpString:             50,
		AttackString:         64,
		DefenseString:        50,
		SpecialAttackString:  45,
		SpecialDefenseString: 50,
		SpeedString:          41,
	},
	"Pupitar": {
		HpString:             70,
		AttackString:         84,
		DefenseString:        70,
		SpecialAttackString:  65,
		SpecialDefenseString: 70,
		SpeedString:          51,
	},
	"Tyranitar": {
		HpString:             100,
		AttackString:         134,
		DefenseString:        110,
		SpecialAttackString:  95,
		SpecialDefenseString: 100,
		SpeedString:          61,
	},
	"Lugia": {
		HpString:             106,
		AttackString:         90,
		DefenseString:        130,
		SpecialAttackString:  90,
		SpecialDefenseString: 154,
		SpeedString:          110,
	},
	"Ho-oh": {
		HpString:             106,
		AttackString:         130,
		DefenseString:        90,
		SpecialAttackString:  110,
		SpecialDefenseString: 154,
		SpeedString:          90,
	},
	"Celebi": {
		HpString:             100,
		AttackString:         100,
		DefenseString:        100,
		SpecialAttackString:  100,
		SpecialDefenseString: 100,
		SpeedString:          100,
	},
	"Treecko": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        35,
		SpecialAttackString:  65,
		SpecialDefenseString: 55,
		SpeedString:          70,
	},
	"Grovyle": {
		HpString:             50,
		AttackString:         65,
		DefenseString:        45,
		SpecialAttackString:  85,
		SpecialDefenseString: 65,
		SpeedString:          95,
	},
	"Sceptile": {
		HpString:             70,
		AttackString:         85,
		DefenseString:        65,
		SpecialAttackString:  105,
		SpecialDefenseString: 85,
		SpeedString:          120,
	},
	"Torchic": {
		HpString:             45,
		AttackString:         60,
		DefenseString:        40,
		SpecialAttackString:  70,
		SpecialDefenseString: 50,
		SpeedString:          45,
	},
	"Combusken": {
		HpString:             60,
		AttackString:         85,
		DefenseString:        60,
		SpecialAttackString:  85,
		SpecialDefenseString: 60,
		SpeedString:          55,
	},
	"Blaziken": {
		HpString:             80,
		AttackString:         120,
		DefenseString:        70,
		SpecialAttackString:  110,
		SpecialDefenseString: 70,
		SpeedString:          80,
	},
	"Mudkip": {
		HpString:             50,
		AttackString:         70,
		DefenseString:        50,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          40,
	},
	"Marshtomp": {
		HpString:             70,
		AttackString:         85,
		DefenseString:        70,
		SpecialAttackString:  60,
		SpecialDefenseString: 70,
		SpeedString:          50,
	},
	"Swampert": {
		HpString:             100,
		AttackString:         110,
		DefenseString:        90,
		SpecialAttackString:  85,
		SpecialDefenseString: 90,
		SpeedString:          60,
	},
	"Poochyena": {
		HpString:             35,
		AttackString:         55,
		DefenseString:        35,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          35,
	},
	"Mightyena": {
		HpString:             70,
		AttackString:         90,
		DefenseString:        70,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          70,
	},
	"Zigzagoon": {
		HpString:             38,
		AttackString:         30,
		DefenseString:        41,
		SpecialAttackString:  30,
		SpecialDefenseString: 41,
		SpeedString:          60,
	},
	"Linoone": {
		HpString:             78,
		AttackString:         70,
		DefenseString:        61,
		SpecialAttackString:  50,
		SpecialDefenseString: 61,
		SpeedString:          100,
	},
	"Wurmple": {
		HpString:             45,
		AttackString:         45,
		DefenseString:        35,
		SpecialAttackString:  20,
		SpecialDefenseString: 30,
		SpeedString:          20,
	},
	"Silcoon": {
		HpString:             50,
		AttackString:         35,
		DefenseString:        55,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          15,
	},
	"Beautifly": {
		HpString:             60,
		AttackString:         70,
		DefenseString:        50,
		SpecialAttackString:  90,
		SpecialDefenseString: 50,
		SpeedString:          65,
	},
	"Cascoon": {
		HpString:             50,
		AttackString:         35,
		DefenseString:        55,
		SpecialAttackString:  25,
		SpecialDefenseString: 25,
		SpeedString:          15,
	},
	"Dustox": {
		HpString:             60,
		AttackString:         50,
		DefenseString:        70,
		SpecialAttackString:  50,
		SpecialDefenseString: 90,
		SpeedString:          65,
	},
	"Lotad": {
		HpString:             40,
		AttackString:         30,
		DefenseString:        30,
		SpecialAttackString:  40,
		SpecialDefenseString: 50,
		SpeedString:          30,
	},
	"Lombre": {
		HpString:             60,
		AttackString:         50,
		DefenseString:        50,
		SpecialAttackString:  60,
		SpecialDefenseString: 70,
		SpeedString:          50,
	},
	"Ludicolo": {
		HpString:             80,
		AttackString:         70,
		DefenseString:        70,
		SpecialAttackString:  90,
		SpecialDefenseString: 100,
		SpeedString:          70,
	},
	"Seedot": {
		HpString:             40,
		AttackString:         40,
		DefenseString:        50,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          30,
	},
	"Nuzleaf": {
		HpString:             70,
		AttackString:         70,
		DefenseString:        40,
		SpecialAttackString:  60,
		SpecialDefenseString: 40,
		SpeedString:          60,
	},
	"Shiftry": {
		HpString:             90,
		AttackString:         100,
		DefenseString:        60,
		SpecialAttackString:  90,
		SpecialDefenseString: 60,
		SpeedString:          80,
	},
	"Taillow": {
		HpString:             40,
		AttackString:         55,
		DefenseString:        30,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          85,
	},
	"Swellow": {
		HpString:             60,
		AttackString:         85,
		DefenseString:        60,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          125,
	},
	"Wingull": {
		HpString:             40,
		AttackString:         30,
		DefenseString:        30,
		SpecialAttackString:  55,
		SpecialDefenseString: 30,
		SpeedString:          85,
	},
	"Pelipper": {
		HpString:             60,
		AttackString:         50,
		DefenseString:        100,
		SpecialAttackString:  85,
		SpecialDefenseString: 70,
		SpeedString:          65,
	},
	"Ralts": {
		HpString:             28,
		AttackString:         25,
		DefenseString:        25,
		SpecialAttackString:  45,
		SpecialDefenseString: 35,
		SpeedString:          40,
	},
	"Kirlia": {
		HpString:             38,
		AttackString:         35,
		DefenseString:        35,
		SpecialAttackString:  65,
		SpecialDefenseString: 55,
		SpeedString:          50,
	},
	"Gardevoir": {
		HpString:             68,
		AttackString:         65,
		DefenseString:        65,
		SpecialAttackString:  125,
		SpecialDefenseString: 115,
		SpeedString:          80,
	},
	"Surskit": {
		HpString:             40,
		AttackString:         30,
		DefenseString:        32,
		SpecialAttackString:  50,
		SpecialDefenseString: 52,
		SpeedString:          65,
	},
	"Masquerain": {
		HpString:             70,
		AttackString:         60,
		DefenseString:        62,
		SpecialAttackString:  80,
		SpecialDefenseString: 82,
		SpeedString:          60,
	},
	"Shroomish": {
		HpString:             60,
		AttackString:         40,
		DefenseString:        60,
		SpecialAttackString:  40,
		SpecialDefenseString: 60,
		SpeedString:          35,
	},
	"Breloom": {
		HpString:             60,
		AttackString:         130,
		DefenseString:        80,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          70,
	},
	"Slakoth": {
		HpString:             60,
		AttackString:         60,
		DefenseString:        60,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          30,
	},
	"Vigoroth": {
		HpString:             80,
		AttackString:         80,
		DefenseString:        80,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          90,
	},
	"Slaking": {
		HpString:             150,
		AttackString:         160,
		DefenseString:        100,
		SpecialAttackString:  95,
		SpecialDefenseString: 65,
		SpeedString:          100,
	},
	"Nincada": {
		HpString:             31,
		AttackString:         45,
		DefenseString:        90,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          40,
	},
	"Ninjask": {
		HpString:             61,
		AttackString:         90,
		DefenseString:        45,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          160,
	},
	"Shedinja": {
		HpString:             1,
		AttackString:         90,
		DefenseString:        45,
		SpecialAttackString:  30,
		SpecialDefenseString: 30,
		SpeedString:          40,
	},
	"Whismur": {
		HpString:             64,
		AttackString:         51,
		DefenseString:        23,
		SpecialAttackString:  51,
		SpecialDefenseString: 23,
		SpeedString:          28,
	},
	"Loudred": {
		HpString:             84,
		AttackString:         71,
		DefenseString:        43,
		SpecialAttackString:  71,
		SpecialDefenseString: 43,
		SpeedString:          48,
	},
	"Exploud": {
		HpString:             104,
		AttackString:         91,
		DefenseString:        63,
		SpecialAttackString:  91,
		SpecialDefenseString: 63,
		SpeedString:          68,
	},
	"Makuhita": {
		HpString:             72,
		AttackString:         60,
		DefenseString:        30,
		SpecialAttackString:  20,
		SpecialDefenseString: 30,
		SpeedString:          25,
	},
	"Hariyama": {
		HpString:             144,
		AttackString:         120,
		DefenseString:        60,
		SpecialAttackString:  40,
		SpecialDefenseString: 60,
		SpeedString:          50,
	},
	"Azurill": {
		HpString:             50,
		AttackString:         20,
		DefenseString:        40,
		SpecialAttackString:  20,
		SpecialDefenseString: 40,
		SpeedString:          20,
	},
	"Nosepass": {
		HpString:             30,
		AttackString:         45,
		DefenseString:        135,
		SpecialAttackString:  45,
		SpecialDefenseString: 90,
		SpeedString:          30,
	},
	"Skitty": {
		HpString:             50,
		AttackString:         45,
		DefenseString:        45,
		SpecialAttackString:  35,
		SpecialDefenseString: 35,
		SpeedString:          50,
	},
	"Delcatty": {
		HpString:             70,
		AttackString:         65,
		DefenseString:        65,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          70,
	},
	"Sableye": {
		HpString:             50,
		AttackString:         75,
		DefenseString:        75,
		SpecialAttackString:  65,
		SpecialDefenseString: 65,
		SpeedString:          50,
	},
	"Mawile": {
		HpString:             50,
		AttackString:         85,
		DefenseString:        85,
		SpecialAttackString:  55,
		SpecialDefenseString: 55,
		SpeedString:          50,
	},
	"Aron": {
		HpString:             50,
		AttackString:         70,
		DefenseString:        100,
		SpecialAttackString:  40,
		SpecialDefenseString: 40,
		SpeedString:          30,
	},
	"Lairon": {
		HpString:             60,
		AttackString:         90,
		DefenseString:        140,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          40,
	},
	"Aggron": {
		HpString:             70,
		AttackString:         110,
		DefenseString:        180,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          50,
	},
	"Meditite": {
		HpString:             30,
		AttackString:         40,
		DefenseString:        55,
		SpecialAttackString:  40,
		SpecialDefenseString: 55,
		SpeedString:          60,
	},
	"Medicham": {
		HpString:             60,
		AttackString:         60,
		DefenseString:        75,
		SpecialAttackString:  60,
		SpecialDefenseString: 75,
		SpeedString:          80,
	},
	"Electrike": {
		HpString:             40,
		AttackString:         45,
		DefenseString:        40,
		SpecialAttackString:  65,
		SpecialDefenseString: 40,
		SpeedString:          65,
	},
	"Manectric": {
		HpString:             70,
		AttackString:         75,
		DefenseString:        60,
		SpecialAttackString:  105,
		SpecialDefenseString: 60,
		SpeedString:          105,
	},
	"Plusle": {
		HpString:             60,
		AttackString:         50,
		DefenseString:        40,
		SpecialAttackString:  85,
		SpecialDefenseString: 75,
		SpeedString:          95,
	},
	"Minun": {
		HpString:             60,
		AttackString:         40,
		DefenseString:        50,
		SpecialAttackString:  75,
		SpecialDefenseString: 85,
		SpeedString:          95,
	},
	"Volbeat": {
		HpString:             65,
		AttackString:         73,
		DefenseString:        55,
		SpecialAttackString:  47,
		SpecialDefenseString: 75,
		SpeedString:          85,
	},
	"Illumise": {
		HpString:             65,
		AttackString:         47,
		DefenseString:        55,
		SpecialAttackString:  73,
		SpecialDefenseString: 75,
		SpeedString:          85,
	},
	"Roselia": {
		HpString:             50,
		AttackString:         60,
		DefenseString:        45,
		SpecialAttackString:  100,
		SpecialDefenseString: 80,
		SpeedString:          65,
	},
	"Gulpin": {
		HpString:             70,
		AttackString:         43,
		DefenseString:        53,
		SpecialAttackString:  43,
		SpecialDefenseString: 53,
		SpeedString:          40,
	},
	"Swalot": {
		HpString:             100,
		AttackString:         73,
		DefenseString:        83,
		SpecialAttackString:  73,
		SpecialDefenseString: 83,
		SpeedString:          55,
	},
	"Carvanha": {
		HpString:             45,
		AttackString:         90,
		DefenseString:        20,
		SpecialAttackString:  65,
		SpecialDefenseString: 20,
		SpeedString:          65,
	},
	"Sharpedo": {
		HpString:             70,
		AttackString:         120,
		DefenseString:        40,
		SpecialAttackString:  95,
		SpecialDefenseString: 40,
		SpeedString:          95,
	},
	"Wailmer": {
		HpString:             130,
		AttackString:         70,
		DefenseString:        35,
		SpecialAttackString:  70,
		SpecialDefenseString: 35,
		SpeedString:          60,
	},
	"Wailord": {
		HpString:             170,
		AttackString:         90,
		DefenseString:        45,
		SpecialAttackString:  90,
		SpecialDefenseString: 45,
		SpeedString:          60,
	},
	"Numel": {
		HpString:             60,
		AttackString:         60,
		DefenseString:        40,
		SpecialAttackString:  65,
		SpecialDefenseString: 45,
		SpeedString:          35,
	},
	"Camerupt": {
		HpString:             70,
		AttackString:         100,
		DefenseString:        70,
		SpecialAttackString:  105,
		SpecialDefenseString: 75,
		SpeedString:          40,
	},
	"Torkoal": {
		HpString:             70,
		AttackString:         85,
		DefenseString:        140,
		SpecialAttackString:  85,
		SpecialDefenseString: 70,
		SpeedString:          20,
	},
	"Spoink": {
		HpString:             60,
		AttackString:         25,
		DefenseString:        35,
		SpecialAttackString:  70,
		SpecialDefenseString: 80,
		SpeedString:          60,
	},
	"Grumpig": {
		HpString:             80,
		AttackString:         45,
		DefenseString:        65,
		SpecialAttackString:  90,
		SpecialDefenseString: 110,
		SpeedString:          80,
	},
	"Spinda": {
		HpString:             60,
		AttackString:         60,
		DefenseString:        60,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          60,
	},
	"Trapinch": {
		HpString:             45,
		AttackString:         100,
		DefenseString:        45,
		SpecialAttackString:  45,
		SpecialDefenseString: 45,
		SpeedString:          10,
	},
	"Vibrava": {
		HpString:             50,
		AttackString:         70,
		DefenseString:        50,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          70,
	},
	"Flygon": {
		HpString:             80,
		AttackString:         100,
		DefenseString:        80,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          100,
	},
	"Cacnea": {
		HpString:             50,
		AttackString:         85,
		DefenseString:        40,
		SpecialAttackString:  85,
		SpecialDefenseString: 40,
		SpeedString:          35,
	},
	"Cacturne": {
		HpString:             70,
		AttackString:         115,
		DefenseString:        60,
		SpecialAttackString:  115,
		SpecialDefenseString: 60,
		SpeedString:          55,
	},
	"Swablu": {
		HpString:             45,
		AttackString:         40,
		DefenseString:        60,
		SpecialAttackString:  40,
		SpecialDefenseString: 75,
		SpeedString:          50,
	},
	"Altaria": {
		HpString:             75,
		AttackString:         70,
		DefenseString:        90,
		SpecialAttackString:  70,
		SpecialDefenseString: 105,
		SpeedString:          80,
	},
	"Zangoose": {
		HpString:             73,
		AttackString:         115,
		DefenseString:        60,
		SpecialAttackString:  60,
		SpecialDefenseString: 60,
		SpeedString:          90,
	},
	"Seviper": {
		HpString:             73,
		AttackString:         100,
		DefenseString:        60,
		SpecialAttackString:  100,
		SpecialDefenseString: 60,
		SpeedString:          65,
	},
	"Lunatone": {
		HpString:             70,
		AttackString:         55,
		DefenseString:        65,
		SpecialAttackString:  95,
		SpecialDefenseString: 85,
		SpeedString:          70,
	},
	"Solrock": {
		HpString:             70,
		AttackString:         95,
		DefenseString:        85,
		SpecialAttackString:  55,
		SpecialDefenseString: 65,
		SpeedString:          70,
	},
	"Barboach": {
		HpString:             50,
		AttackString:         48,
		DefenseString:        43,
		SpecialAttackString:  46,
		SpecialDefenseString: 41,
		SpeedString:          60,
	},
	"Whiscash": {
		HpString:             110,
		AttackString:         78,
		DefenseString:        73,
		SpecialAttackString:  76,
		SpecialDefenseString: 71,
		SpeedString:          60,
	},
	"Corphish": {
		HpString:             43,
		AttackString:         80,
		DefenseString:        65,
		SpecialAttackString:  50,
		SpecialDefenseString: 35,
		SpeedString:          35,
	},
	"Crawdaunt": {
		HpString:             63,
		AttackString:         120,
		DefenseString:        85,
		SpecialAttackString:  90,
		SpecialDefenseString: 55,
		SpeedString:          55,
	},
	"Baltoy": {
		HpString:             40,
		AttackString:         40,
		DefenseString:        55,
		SpecialAttackString:  40,
		SpecialDefenseString: 70,
		SpeedString:          55,
	},
	"Claydol": {
		HpString:             60,
		AttackString:         70,
		DefenseString:        105,
		SpecialAttackString:  70,
		SpecialDefenseString: 120,
		SpeedString:          75,
	},
	"Lileep": {
		HpString:             66,
		AttackString:         41,
		DefenseString:        77,
		SpecialAttackString:  61,
		SpecialDefenseString: 87,
		SpeedString:          23,
	},
	"Cradily": {
		HpString:             86,
		AttackString:         81,
		DefenseString:        97,
		SpecialAttackString:  81,
		SpecialDefenseString: 107,
		SpeedString:          43,
	},
	"Anorith": {
		HpString:             45,
		AttackString:         95,
		DefenseString:        50,
		SpecialAttackString:  40,
		SpecialDefenseString: 50,
		SpeedString:          75,
	},
	"Armaldo": {
		HpString:             75,
		AttackString:         125,
		DefenseString:        100,
		SpecialAttackString:  70,
		SpecialDefenseString: 80,
		SpeedString:          45,
	},
	"Feebas": {
		HpString:             20,
		AttackString:         15,
		DefenseString:        20,
		SpecialAttackString:  10,
		SpecialDefenseString: 55,
		SpeedString:          80,
	},
	"Milotic": {
		HpString:             95,
		AttackString:         60,
		DefenseString:        79,
		SpecialAttackString:  100,
		SpecialDefenseString: 125,
		SpeedString:          81,
	},
	"Castform": {
		HpString:             70,
		AttackString:         70,
		DefenseString:        70,
		SpecialAttackString:  70,
		SpecialDefenseString: 70,
		SpeedString:          70,
	},
	"Kecleon": {
		HpString:             60,
		AttackString:         90,
		DefenseString:        70,
		SpecialAttackString:  60,
		SpecialDefenseString: 120,
		SpeedString:          40,
	},
	"Shuppet": {
		HpString:             44,
		AttackString:         75,
		DefenseString:        35,
		SpecialAttackString:  63,
		SpecialDefenseString: 33,
		SpeedString:          45,
	},
	"Banette": {
		HpString:             64,
		AttackString:         115,
		DefenseString:        65,
		SpecialAttackString:  83,
		SpecialDefenseString: 63,
		SpeedString:          65,
	},
	"Duskull": {
		HpString:             20,
		AttackString:         40,
		DefenseString:        90,
		SpecialAttackString:  30,
		SpecialDefenseString: 90,
		SpeedString:          25,
	},
	"Dusclops": {
		HpString:             40,
		AttackString:         70,
		DefenseString:        130,
		SpecialAttackString:  60,
		SpecialDefenseString: 130,
		SpeedString:          25,
	},
	"Tropius": {
		HpString:             99,
		AttackString:         68,
		DefenseString:        83,
		SpecialAttackString:  72,
		SpecialDefenseString: 87,
		SpeedString:          51,
	},
	"Chimecho": {
		HpString:             65,
		AttackString:         50,
		DefenseString:        70,
		SpecialAttackString:  95,
		SpecialDefenseString: 80,
		SpeedString:          65,
	},
	"Absol": {
		HpString:             65,
		AttackString:         130,
		DefenseString:        60,
		SpecialAttackString:  75,
		SpecialDefenseString: 60,
		SpeedString:          75,
	},
	"Wynaut": {
		HpString:             95,
		AttackString:         23,
		DefenseString:        48,
		SpecialAttackString:  23,
		SpecialDefenseString: 48,
		SpeedString:          23,
	},
	"Snorunt": {
		HpString:             50,
		AttackString:         50,
		DefenseString:        50,
		SpecialAttackString:  50,
		SpecialDefenseString: 50,
		SpeedString:          50,
	},
	"Glalie": {
		HpString:             80,
		AttackString:         80,
		DefenseString:        80,
		SpecialAttackString:  80,
		SpecialDefenseString: 80,
		SpeedString:          80,
	},
	"Spheal": {
		HpString:             70,
		AttackString:         40,
		DefenseString:        50,
		SpecialAttackString:  55,
		SpecialDefenseString: 50,
		SpeedString:          25,
	},
	"Sealeo": {
		HpString:             90,
		AttackString:         60,
		DefenseString:        70,
		SpecialAttackString:  75,
		SpecialDefenseString: 70,
		SpeedString:          45,
	},
	"Walrein": {
		HpString:             110,
		AttackString:         80,
		DefenseString:        90,
		SpecialAttackString:  95,
		SpecialDefenseString: 90,
		SpeedString:          65,
	},
	"Clamperl": {
		HpString:             35,
		AttackString:         64,
		DefenseString:        85,
		SpecialAttackString:  74,
		SpecialDefenseString: 55,
		SpeedString:          32,
	},
	"Huntail": {
		HpString:             55,
		AttackString:         104,
		DefenseString:        105,
		SpecialAttackString:  94,
		SpecialDefenseString: 75,
		SpeedString:          52,
	},
	"Gorebyss": {
		HpString:             55,
		AttackString:         84,
		DefenseString:        105,
		SpecialAttackString:  114,
		SpecialDefenseString: 75,
		SpeedString:          52,
	},
	"Relicanth": {
		HpString:             100,
		AttackString:         90,
		DefenseString:        130,
		SpecialAttackString:  45,
		SpecialDefenseString: 65,
		SpeedString:          55,
	},
	"Luvdisc": {
		HpString:             43,
		AttackString:         30,
		DefenseString:        55,
		SpecialAttackString:  40,
		SpecialDefenseString: 65,
		SpeedString:          97,
	},
	"Bagon": {
		HpString:             45,
		AttackString:         75,
		DefenseString:        60,
		SpecialAttackString:  40,
		SpecialDefenseString: 30,
		SpeedString:          50,
	},
	"Shelgon": {
		HpString:             65,
		AttackString:         95,
		DefenseString:        100,
		SpecialAttackString:  60,
		SpecialDefenseString: 50,
		SpeedString:          50,
	},
	"Salamence": {
		HpString:             95,
		AttackString:         135,
		DefenseString:        80,
		SpecialAttackString:  110,
		SpecialDefenseString: 80,
		SpeedString:          100,
	},
	"Beldum": {
		HpString:             40,
		AttackString:         55,
		DefenseString:        80,
		SpecialAttackString:  35,
		SpecialDefenseString: 60,
		SpeedString:          30,
	},
	"Metang": {
		HpString:             60,
		AttackString:         75,
		DefenseString:        100,
		SpecialAttackString:  55,
		SpecialDefenseString: 80,
		SpeedString:          50,
	},
	"Metagross": {
		HpString:             80,
		AttackString:         135,
		DefenseString:        130,
		SpecialAttackString:  95,
		SpecialDefenseString: 90,
		SpeedString:          70,
	},
	"Regirock": {
		HpString:             80,
		AttackString:         100,
		DefenseString:        200,
		SpecialAttackString:  50,
		SpecialDefenseString: 100,
		SpeedString:          50,
	},
	"Regice": {
		HpString:             80,
		AttackString:         50,
		DefenseString:        100,
		SpecialAttackString:  100,
		SpecialDefenseString: 200,
		SpeedString:          50,
	},
	"Registeel": {
		HpString:             80,
		AttackString:         75,
		DefenseString:        150,
		SpecialAttackString:  75,
		SpecialDefenseString: 150,
		SpeedString:          50,
	},
	"Latias": {
		HpString:             80,
		AttackString:         80,
		DefenseString:        90,
		SpecialAttackString:  110,
		SpecialDefenseString: 130,
		SpeedString:          110,
	},
	"Latios": {
		HpString:             80,
		AttackString:         90,
		DefenseString:        80,
		SpecialAttackString:  130,
		SpecialDefenseString: 110,
		SpeedString:          110,
	},
	"Kyogre": {
		HpString:             100,
		AttackString:         100,
		DefenseString:        90,
		SpecialAttackString:  150,
		SpecialDefenseString: 140,
		SpeedString:          90,
	},
	"Groudon": {
		HpString:             100,
		AttackString:         150,
		DefenseString:        140,
		SpecialAttackString:  100,
		SpecialDefenseString: 90,
		SpeedString:          90,
	},
	"Rayquaza": {
		HpString:             105,
		AttackString:         150,
		DefenseString:        90,
		SpecialAttackString:  150,
		SpecialDefenseString: 90,
		SpeedString:          95,
	},
	"Jirachi": {
		HpString:             100,
		AttackString:         100,
		DefenseString:        100,
		SpecialAttackString:  100,
		SpecialDefenseString: 100,
		SpeedString:          100,
	},
	"Deoxys": {
		HpString:             50,
		AttackString:         150,
		DefenseString:        50,
		SpecialAttackString:  150,
		SpecialDefenseString: 50,
		SpeedString:          150,
	},
	"Deoxys-atk": {
		HpString:             50,
		AttackString:         180,
		DefenseString:        20,
		SpecialAttackString:  180,
		SpecialDefenseString: 20,
		SpeedString:          150,
	},
	"Deoxys-def": {
		HpString:             50,
		AttackString:         70,
		DefenseString:        160,
		SpecialAttackString:  70,
		SpecialDefenseString: 160,
		SpeedString:          90,
	},
	"Deoxys-spd": {
		HpString:             50,
		AttackString:         95,
		DefenseString:        90,
		SpecialAttackString:  95,
		SpecialDefenseString: 90,
		SpeedString:          180,
	},
}
